### PR TITLE
Remove .ino extension from firmware name

### LINKED ISSUE #421: [standard mismatch] "Query Firmware" returns file name WITH extension
Hello, [protocol.md](https://github.com/firmata/protocol/blob/master/protocol.md) says    

>The firmware name to be reported should be exactly the same as the name of the Firmata client file, minus the file extension. So for StandardFirmata.ino, the firmware name is: StandardFirmata.

But indeed file name is passed **with** extension.

I think it may be fixed by adding modifying 
[`extension = strstr(name, ".cpp");`](https://github.com/firmata/arduino/blob/master/Firmata.cpp#L207) 
to 
```
extension = strstr(name, ".cpp");
if (!extension)
  extension = strstr(name, ".ino");
```

Issue present in StandardFirmata from Arduino IDE v1.8.8.

### PR DESCRIPTION
**Pull request by mexchip**
Closes #421

### CODE REVIEW

**Comment by mexchip** [comment]
Relevant changes are in lines 221-223, changes at lines 81 and 269 (previously 266) are formatting changes after running astyle with the indicated options in the _Contributing_ section (two spaces indenting)

**Comment by mexchip** [comment]
Tested with _StandardFirmata_ firmware in a Sparkfun RedBoard (Arduino/Genuino Uno compatible), querying firmware version using PyMata3:
```python
from pymata_aio.pymata3 import PyMata3
from pymata_aio.constants import Constants

board = PyMata3()
```
Before:
```
pymata_aio Version 2.31	Copyright (c) 2015-2018 Alan Yorinks All rights reserved.

Using COM Port:/dev/ttyUSB0

Initializing Arduino - Please wait... 
Arduino Firmware ID: 2.5 StandardFirmata.ino
Auto-discovery complete. Found 20 Digital Pins and 6 Analog Pins
```
After
```
pymata_aio Version 2.31	Copyright (c) 2015-2018 Alan Yorinks All rights reserved.

Using COM Port:/dev/ttyUSB0

Initializing Arduino - Please wait... 
Arduino Firmware ID: 2.5 StandardFirmata
Auto-discovery complete. Found 20 Digital Pins and 6 Analog Pins
```

**Comment by soundanalogous** [comment]
My concern with this change is that the extension has always been included (even though the protocol description contradicts that) and there may be user applications that string match against the firmware name including the extension, so changing this will break those applications.

**Comment by mexchip** [comment]
That's true, guess it'd be better to just update the docs?

**Comment by mexchip** [comment]
Clossing this as discussed [here](https://github.com/firmata/arduino/issues/421#issuecomment-547564231).

**Pull request closed without merging**
