### PR TITLE
Add support for Arduino Zero

### PR DESCRIPTION
**Pull request by soundanalogous**
You will need an official Arduino Pro Zero board. Do not get an M0 Pro board, that will not work with Firmata.

In order to use, you'll have to make sure the Servo library is at least version 1.1.0.  Follow these instructions:
1. In the Arduino IDE (the arduino.cc one), go to Sketch > Include libraries > Manage libraries.
2. Search for "Servo" and scroll down the results list to "Servo by Michael Margolis..."
3. Tap on the list item (I wish this was more clear in the UI), then an option to Update will appear
4. Click on update.

TODO:
- [x] Ensure only digital I/O pins are reset in `systemResetCallback`
- [ ] Thorough testing

### CODE REVIEW

**Comment by soundanalogous** [comment]
This is going to push out the v2.5 release at least a week while I wait for my Zero board to arrive.

**Comment by rwaldron** [comment]
Can you link to the Zero you ordered? I don't want to order the wrong thing again.

**Comment by soundanalogous** [comment]
I ordered direct from arduino.cc: http://store-usa.arduino.cc/products/abx00003

**Comment by soundanalogous** [comment]
Zero does not yet seem to be very stable yet. I'm seeing strange issues like digital pins no longer working when a pwm pin is in use on the same port. Need to do more testing with regular Arduino sketches to isolate the issues (what is Firmata-related and what is weirdness with Zero).

**Comment by soundanalogous** [comment]
Zero does not like this: https://github.com/firmata/arduino/blob/master/examples/StandardFirmata/StandardFirmata.ino#L266. Commenting out that line will enable digital input. However it still does not solve all problems I'm seeing.

**Comment by soundanalogous** [comment]
Issue with Zero per previous comment is describe here: https://github.com/firmata/arduino/issues/231

**Comment by soundanalogous** [comment]
Turns out for Zero, internal pull-ups can only be set by setting the pinMode to INPUT_PULLUP so the last commit does not help the Zero situation.

**Comment by soundanalogous** [comment]
Fixed internal pull-up issue in [last commit](https://github.com/firmata/arduino/commit/8ab43c3f5be036f87da27b64a13708c6895c653f).

**Pull request merged**
