### PR TITLE
Add StandardFirmataEthernet example

### PR DESCRIPTION
**Pull request by soundanalogous**
StandardFirmataEthernet works with the Arduino Ethernet board, Arduino Ethernet Shield and the Arduino Yun.

Has been tested successfully with and Arduino Ethernet Shield attached to an Arduino Uno and also with an Arduino Yun (using the on-board ethernet jack). I'm using the eg/blink-firmata.js and blink-johnny-five.js examples of the [etherport repo](https://github.com/rwaldron/etherport) for the client side test.

Tested successfully with the following boards and an Arduino Ethernet shield:
- Arduino Uno
- Arduino Leonardo
- Arduino Mega
- Arduino Due

### CODE REVIEW

**Comment by rwaldron** [comment]
I wrote up a guide for getting started for this as well -> https://github.com/rwaldron/etherport

**Comment by soundanalogous** [comment]
Successfully tested StandardFirmataEthernet using Arduino Uno, Arduino Mega and Arduino Due with an Arduino Ethernet Shield. It is not working however with Arduino Leonardo. Looking into this further...

**Comment by soundanalogous** [comment]
Removed UIPEthernet option. It uses too much memory and I can't get it to work properly.

**Comment by tarek360** [comment]
Can i sue StandardFirmataEthernet with Arduino Leonardo?

**Comment by soundanalogous** [comment]
Yes, I have successfully used StandardFirmataEthernet with an Arduino Leonardo with an attached Arduino Ethernet shield.

**Comment by tarek360** [comment]
This is a very good news for me :)
But how can i control on remote Arduino Leonardo with an attached Arduino Ethernet shield using StandardFirmataEthernet, johnny-five and Internet connection without local USB connection ??

i have used this code to connect locally
var five = require("johnny-five");
var board = new five.Board();
board.on("ready", function() {
  var led = new five.Led(13);
  led.blink(500);
});

but i want to connect to the remote Arduino throw Internet
if you can help me about how to configure StandardFirmataEthernet and what is the code in  johnny-five to connect to the remote Arduino?

Thank You.

**Comment by soundanalogous** [comment]
You need to use [Etherport](https://github.com/rwaldron/etherport)

**Comment by tarek360** [comment]
Thanks man i appreciate your help,
I already used Etherport but it didn't work with me, if it works with you i
will try again maybe i miss something.

Thanks :)

**Comment by rwaldron** [comment]
@tarek360 Please file a bug here: https://github.com/rwaldron/etherport/issues Thanks!

**Pull request merged**
