### PR TITLE
Removed some spelling mistakes in the comments

### PR DESCRIPTION
**Pull request by shantanu69**
In line 6 the `clink` should be click and in line 7 there should be a `in` before `your default browser`

### CODE REVIEW

**Comment by soundanalogous** [comment]
Thanks for catching this. Could you make the same change in all of the StandardFirmata... files?

**Comment by shantanu69** [comment]
Okay, I will see :+1:

**Comment by shantanu69** [comment]
@soundanalogous How about now?

**Comment by soundanalogous** [comment]
perfect. thank you!

**Pull request merged**
