### PR TITLE
Abstract FirmataParser memory allocation scheme

### PR DESCRIPTION
**Pull request by zfields**
This is ready for testing. I haven't had any opportunity to test this between hardware, but it does pass the test suite.

I wanted to share what I'm working on, so I could get feedback. I think it resolves the memory allocation concerns @soundanalogous pointed out in issue #328, and it can also handle my desire to utilize `realloc()`.

I will report back once I've had an opportunity to test.
[EDIT] I have confirmed it works with Windows Remote Arduino.
[EDIT] I have confirmed it works as expected on Linux.

### CODE REVIEW

**Comment by soundanalogous** [comment]
I think we definitely need unit tests for the Parser to ensure all expected cases are covered. The test suit should also ensure there are no memory leaks.

**Comment by zfields** [comment]
This pull request relieves FirmataParser of the ownership of buffer. As a result, the parser can not cause a memory leak.
I haven't changed the parsing logic, only the buffering logic.

Currently, I am in the middle of my prototype, and I don't have time to write any test. I was hoping to be able to complete my prototype without forking your repo. If we can run this through your board tests this weekend and pull it in, I won't send you another change to the parser without first writing some tests.

**Comment by soundanalogous** [comment]
Ok I will run it through my board tests tomorrow.

**Comment by soundanalogous** [comment]
I get a compiler warning when compiling for the following boards (some compilers are more picky than others):

- Arduino 101
- Teensy 2.0/LC/3.1/3.2/3.5/3.6

```
/Users/soundanalogous/Google Drive/Arduino/libraries/Firmata/src/FirmataParser.cpp: In member function ‘bool FirmataParser::bufferDataAtPosition(uint8_t, size_t)’:
/Users/soundanalogous/Google Drive/Arduino/libraries/Firmata/src/FirmataParser.cpp:302:8: warning: unused variable ‘writeError’ [-Wunused-variable]
   bool writeError = false;
```

**Comment by soundanalogous** [comment]
I get a compiler error when compiling for an Arduino Uno, Mega and Teensy 2.0 (all AVR boards) in Arduino 1.0.6:

```
In file included from StandardFirmata.ino:28:
/Applications/arduino-1.0.6/Arduino.app/Contents/Resources/Java/libraries/Firmata/Firmata.h:102: error: 'FirmataClass::parserBuffer' cannot appear in a constant-expression
/Applications/arduino-1.0.6/Arduino.app/Contents/Resources/Java/libraries/Firmata/Firmata.h:102: error: ISO C++ forbids initialization of member 'parser'
/Applications/arduino-1.0.6/Arduino.app/Contents/Resources/Java/libraries/Firmata/Firmata.h:102: error: making 'parser' static
/Applications/arduino-1.0.6/Arduino.app/Contents/Resources/Java/libraries/Firmata/Firmata.h:102: error: invalid in-class initialization of static data member of non-integral type 'FirmataParser'
```

**Comment by soundanalogous** [comment]
Other than the above mentioned compiler error and compiler warning, I don't see any issues when running on hardware.

**Comment by zfields** [comment]
@soundanalogous I just got home, and I'll have those cleared up in a moment.

**Comment by zfields** [comment]
@soundanalogous Okay it should be all clear now. I have confirmed the update by talking from Arduino to Linux using the same exact code! :smile:

**Comment by soundanalogous** [comment]
Looks good. All tests are passing. Thanks again!

**Pull request merged**
