### PR TITLE
enable option to auto restart i2c transmission per issue #82

### PR DESCRIPTION
**Pull request by soundanalogous**
see #82

### CODE REVIEW

**Comment by rwaldron** [comment]
I've rebased and updated this patch here: https://github.com/rwaldron/arduino-1/tree/i2c-restart

**Comment by soundanalogous** [comment]
Thanks! Have you had a chance to test it with actual hardware?

**Comment by rwaldron** [comment]
No yet, I had to change gears after I worked on this, but I plan to work on it a bit more tomorrow morning.

**Comment by soundanalogous** [comment]
This branch is a mess. Cherry picking the only 30ce1d5 onto new clean branch and opening new pull requesting. Closing this one.

**Pull request closed without merging**
