### PR TITLE
codec bug

### PR DESCRIPTION
**Pull request by zfields**
#363

### CODE REVIEW

**Comment by zfields** [comment]
I have tested this on all my platforms, and for backward compatibility with 2.5.4.

**Comment by soundanalogous** [comment]
I didn't run https://github.com/firmata/arduino/pull/359 through my tests or I would have caught this. Lesson learned. It's also time we added a string parser test to [firmata_test.ino](https://github.com/firmata/arduino/blob/master/test/firmata_test/firmata_test.ino).

**Comment by soundanalogous** [comment]
See page 29 of [this pdf](http://breakoutjs.com/examples/schematics.pdf). This is the circuit I use to test several features at once (adc, pwm, servo, digital on digital pins, digital I/O on analog pins, I2C read, I2C write). I should really get this made into a shield at some point so other contributors can test with the same setup (and then port the demo app to their respective client libraries). I use Breakout.js for this particular test. The code [is here](https://github.com/soundanalogous/Breakout/blob/master/examples/boards/uno.html) (in case you wanted to create an equivalent example for remote-wiring).

**Comment by soundanalogous** [comment]
Ran through my tests and all is good.

**Pull request merged**
