### PR TITLE
Point to correct library path in Arduino.app

### PR DESCRIPTION
**Pull request by beriberikix**
Libraries are stored in a different path in the latest Arduino.app

### CODE REVIEW

**Comment by soundanalogous** [comment]
I need to update the installation instructions. As of Arduino 1.6.4 Firmata can simply be updated via the Arduino Library Manager:

In the IDE:
1. navigate to: Sketch -> Include Library -> Manage Libraries
2. Filter "Firmata"
3. Tap on the Firmata list item
4. Select the version you want to install (or switch back to) and click Install

This only works for what is in the Master branch. For other branches you'd need to copy Firmata into the 3rd party libraries folder (this works now, but maybe only after using the library manager at least once I think) rather than having to copy into the application directory.

**Comment by beriberikix** [comment]
Ah, right, so glad they did that. But what if you're building from src? For example, I need to modify Boards.h, which could theoretically get massive. It make more sense for the edge-case users to use a forked build, no?

**Comment by soundanalogous** [comment]
Yeah but you should be able to simply clone Firmata to ~/Documents/Arduino/libraries now. That is independent from the Arduino IDE so when you update the IDE you don't need to re-clone.

**Comment by soundanalogous** [comment]
However I have not tried this yet by cloning to libraries dir. It may conflict with the arduino library manager which is targeting the same directory.

**Comment by beriberikix** [comment]
Oh, duh.

**Comment by beriberikix** [comment]
FWIW, I did a fresh install of Arduino on OSX and cloning into /libraries works like a charm. :+1: 

screen shot 2015-08-02 at 10 49 42 am

**Comment by soundanalogous** [comment]
Cool I'll update the instructions in the readme soon.

**Pull request closed without merging**
